### ISSUE TITLE
Retain previous clipboard value when accidentally copied empty link

### ISSUE THREAD

**Issue by srini51293** [parthpanchal123/Linkaro#3]
when we copy the empty link field, I think we should retain the previous clipboard value, isn't it? 
if yes, I think we can replace the **line number 21** in the **app.js** file with  
```
 if(urlData)
      await navigator.clipboard.writeText(urlData);
```

**Comment by parthpanchal123** [comment]
@srini51293 That was a good catch :100: Fixed it :+1:  . Feel free to reopen this just in case !
